package com.bankbroker.loanapp.entity.enums;

public enum ApplicationHistoryStatus {
    IN_PROGRESS,
    APPROVED,
    REJECTED,
    ON_HOLD,
//    CANCELLED,
    VALUATOR_ASSIGNED,
//    ASSIGN_VALUATOR,
    SITE_VISIT_SCHEDULED,
    SITE_VISIT_COMPLETED,
    SITE_VISIT_IN_PROGRESS,
    REVIEWING_APPLICATION,
    SITE_VISIT_FORM_SUBMITTED,
    VALUATOR_REASSIGNED,
    SITE_VISIT_RESCHEDULED,
    APPLICATION_APPLIED

}
